# =============================================================================
# NON-AUTHORITATIVE / SUPERSEDED (stats-revision, 2026-07-06)
# This is a simplified mirror, not a source of manuscript numbers. The
# authoritative engines are:
#   Behaviour : choice R pipeline/scripts/01_pipeline_analysis/
#               activity_analysis_STATS_choice_exp.R
#   Endocrine : choice exp for claude mono and cortisol/claude output/Scripts/
#               analysis_b3.R
# Those two scripts carry the current M1-M5 statistical-revision fixes
# (BH-FDR by brain region, trial-level RE nesting, order/day sensitivity
# test, behaviour<->neurochemistry association). This file has NOT been
# updated to match and may report stale numbers. Do not cite its output in
# the manuscript. See D:\CHOICE R SCRIPTS\STATS_REVISION_INSTRUCTIONS.md
# and stat_map.md for the current source-of-truth mapping.
# =============================================================================

# easy_scripts/by_timepoint/mean_iid_cm_by_tp.R
# -----------------------------------------------------------------------------
# Reproduces res_iid_cm_tp from activity_analysis_STATS_choice_exp.R (see §5/§5b).
# Line-by-line runnable in RStudio. No hidden side effects.
# Generated by _generate_easy_scripts.R from _template_mini_script.R.
# -----------------------------------------------------------------------------

# ---- Step 0: Bridge to main pipeline helpers --------------------------------
# Sources the main STATS file's helpers + theme constants into globalenv.
HERE <- tryCatch(dirname(rstudioapi::getActiveDocumentContext()$path),
                 error = function(e) ".")
ROOT <- if (basename(HERE) %in% c("timepoint_aggregated", "by_timepoint",
                                  "endocrine", "monoamine_per_area"))
  normalizePath(file.path(HERE, "..")) else
  if (basename(dirname(HERE)) == "endocrine")
    normalizePath(file.path(HERE, "..", "..")) else HERE
if (!file.exists(file.path(ROOT, "_helpers.R")))
  ROOT <- file.path(PROJECT_ROOT, "choice R pipeline/easy_scripts")
source(file.path(ROOT, "_re_candidates.R"))
source(file.path(ROOT, "_data_access.R"))
source(file.path(ROOT, "_helpers.R"))

# ---- Step 1: Load -----------------------------------------------------------
dat <- load_behaviour_dataset(require = "mean_iid_cm")
message("Step 1 — Load: ", nrow(dat), " rows x ", ncol(dat), " cols")

# ---- Step 2: Filter / aggregate to model grain ------------------------------
d <- dat %>%
  dplyr::filter(is.finite(mean_iid_cm)) %>%
  dplyr::select(trial_id, phys_trial_id, tank, trial_date, treatment,
                timepoint, timepoint_f, fish_density_f, mean_iid_cm)
message("Step 2 — Filter+aggregate: ", nrow(d),
        " rows ready for Mean inter-individual distance (cm) (by interval)")

# ---- Step 3: Factor levels --------------------------------------------------
d$treatment <- factor(d$treatment, levels = TREATMENT_LEVELS_g)
d$tank <- factor(d$tank)
d$timepoint_f <- factor(d$timepoint_f, levels = TIMEPOINT_LEVELS_g)
d$fish_density_f <- factor(d$fish_density_f, levels = as.character(DENSITY_LEVELS_g))
message("Step 3 — Factors set; treatment levels: ",
        paste(levels(d$treatment), collapse = ", "))

# ---- Step 4: Transformation diagnostics -------------------------------------
cat("Variance:        ", signif(var(d$mean_iid_cm, na.rm = TRUE), 3), "\n")
sw_p <- tryCatch(shapiro.test(d$mean_iid_cm)$p.value, error = function(e) NA_real_)
cat("Shapiro-Wilk p:  ", signif(sw_p, 3), "\n")
cat("N per treatment:\n"); print(table(d$treatment))
message("Step 4 — Diagnostics emitted above")

# ---- Step 5: Candidate RE structures ----------------------------------------
message("Step 5 — RE candidates: ",
        paste(names(RE_WIDE), collapse = "; "))

# ---- Step 6: Fit + AICc-select RE -------------------------------------------
res <- run_lmm_analysis(
  label          = "mean_iid_cm_timepoint",
  data           = d,
  response       = "mean_iid_cm",
  fixed_str      = "treatment * timepoint_f",
  cont_fixed_str = "treatment * timepoint",
  re_cands       = RE_WIDE,
  focal_terms = list(
    "Treatment"           = "^treatment$",
    "Timepoint"           = "^timepoint",
    "Treatment:Timepoint" = "treatment.*timepoint|timepoint.*treatment"
  )
)
`%||%` <- function(a, b) if (is.null(a)) b else a
message("Step 6 — Fixed: ", deparse(res$fixed_formula),
        " | transform: ", res$transform %||% "identity",
        " | family: ",    res$family_used %||% "gaussian",
        " | model class: ", paste(class(res$model), collapse = "/"))

# ---- Step 7: Type-III ANOVA + AICc table ------------------------------------
if (!is.null(res$anova))      print(res$anova)
if (!is.null(res$aicc_table)) {
  cat("\n--- AICc table for RE selection ---\n"); print(res$aicc_table)
}
message("Step 7 — Type III ANOVA + AICc table printed above")

# ---- Step 8: Tukey post hoc + CLD (per focal term) --------------------------
for (.term in names(res$posthoc)) {
  cat("\n=== posthoc for focal term:", .term, "===\n")
  ph <- res$posthoc[[.term]]
  if (!is.null(ph$emmeans))   { cat("\n-- emmeans --\n");   print(ph$emmeans) }
  if (!is.null(ph$contrasts)) { cat("\n-- contrasts --\n"); print(ph$contrasts) }
  if (!is.null(ph$cld))       { cat("\n-- CLD --\n");       print(ph$cld) }
}
message("Step 8 — Tukey + CLD printed above")

# ---- Step 8b: Significant Tukey contrasts only (p < 0.05) ------------------
cat("\n=== SIGNIFICANT CONTRASTS (p < 0.05) ===\n")
.any_sig <- FALSE
for (.term in names(res$posthoc)) {
  ph <- res$posthoc[[.term]]
  if (!is.null(ph$contrasts)) {
    .ct <- tryCatch(as.data.frame(summary(ph$contrasts)), error = function(e) NULL)
    if (!is.null(.ct) && "p.value" %in% names(.ct)) {
      .sig <- .ct[.ct$p.value < 0.05, , drop = FALSE]
      if (nrow(.sig) > 0) {
        cat("\n-- focal term:", .term, "--\n")
        print(.sig)
        .any_sig <- TRUE
      }
    }
  }
}
if (!.any_sig) cat("  (no significant contrasts at p < 0.05)\n")
message("Step 8b — Significant Tukey contrasts (p < 0.05) printed above")

# ---- Step 8c: SIMPLE-EFFECTS (within-stratum) contrasts for interactions ----
# When the focal term is an interaction (e.g. treatment*timepoint_f), the joint
# Tukey across all cells is conservative (28 contrasts for 2x4). The simple-
# effects view tests focal contrasts within each level of a stratifier:
#   ~ treatment | timepoint_f  -> control vs treat AT EACH interval
#   ~ timepoint_f | treatment  -> interval pairs WITHIN each treatment
# These are what typically match patterns shown in the graphs.
cat("\n=== SIMPLE-EFFECTS CONTRASTS (within-stratum, Tukey) ===\n")
.has_simple <- FALSE
for (.term in names(res$posthoc)) {
  ph <- res$posthoc[[.term]]
  if (!is.null(ph$contrasts_simple)) {
    for (.slot in names(ph$contrasts_simple)) {
      .has_simple <- TRUE
      cat("\n-- focal term: ", .term, " | view: ", .slot, " --\n", sep = "")
      cat("  spec: ", ph$contrasts_simple[[.slot]]$spec, "\n")
      .cs <- as.data.frame(ph$contrasts_simple[[.slot]]$contrasts)
      print(.cs)
      if ("p.value" %in% names(.cs)) {
        .sig_s <- .cs[.cs$p.value < 0.05, , drop = FALSE]
        cat("  -> significant rows (p < 0.05):\n")
        if (nrow(.sig_s) > 0) print(.sig_s) else cat("    (none)\n")
      }
    }
  }
}
if (!.has_simple) cat("  (no interaction in model; simple effects not computed)\n")
message("Step 8c — Simple-effects (within-stratum) contrasts printed above")

# ---- Step 9: Raw summary ----------------------------------------------------
raw <- d %>%
  dplyr::group_by(treatment, timepoint_f) %>%
  dplyr::summarise(n = dplyr::n(),
                   mean = mean(mean_iid_cm, na.rm = TRUE),
                   sd   = sd(mean_iid_cm,   na.rm = TRUE),
                   .groups = "drop")
print(raw)
message("Step 9 — Raw mean +/- SD printed above")

# ---- Step 10: Save graph ----------------------------------------------------
p <- .mg_treatment_xaxis(.mg_mk_collective_panel(
  res, y_col = "mean_iid_cm", y_label = "Mean IID (cm)",
  dat = d, show_n = FALSE
))
out_dir <- file.path(ROOT, "outputs", "graphs")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
out_png <- file.path(out_dir, "mean_iid_cm_by_tp.png")
ggplot2::ggsave(out_png, p, width = 140, height = 100,
                units = "mm", dpi = 300)
message("Step 10 — Saved graph to ", out_png)
